image: python:3.8-slim

pages:
    stage: deploy
    script:
        - pip install -r requirements.txt
        - mkdocs build --strict --verbose
    artifacts:
        paths:
            - public
    only:
        - main