name: Deploy Site
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup | Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm i
        working-directory: wiki/.layouts
      # - name: Foam janitor for format markdown files
      #  run: npx foam janitor $(dirname "$PWD")
       # working-directory: wiki/.layouts
      - name: Build Site
        run: npm run build --prefix-paths
        working-directory: wiki/.layouts

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./wiki/.layouts/public
          github_token: ${{ secrets.GITHUB_TOKEN }}
